import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Providers } from "../../providers";

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
  fallback: ["sans-seriv"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-[#f2f2f3ff]`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
