import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Providers } from "../providers";
import Navbar from "./analytics/components/navbar";
import { getServerSession } from "next-auth";
import SessionProvider from "./analytics/components/sessionProvider";
import { Box } from "@chakra-ui/react";
const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
  fallback: ["sans-seriv"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-[#f2f2f3ff]`}>
        <SessionProvider session={session}>
          <Providers>
            <Box className="w-full h-[100vh] overflow-auto pb-20">
              {children}
            </Box>
            <Navbar />
          </Providers>
        </SessionProvider>
      </body>
    </html>
  );
}
